### PR TITLE
Merge branch 'master' into android_set_option_weak_authority

### PR DESCRIPTION
**Pull request by xloem**

### CODE REVIEW

**Comment by crroush** [comment]
I tested this version with a b205mini and Sandisk SD Card reader, both returned value of 0 using  [this](https://github.com/harbulot/LibUsbAndroidIssue942)
I tested with the libusb reference in libusb/libusb#830 and it failed.

**Comment by harbulot** [comment]
Sorry @xloem, I've only just realised you'd opened a PR in my forked repository. Do the newer updates in the PR in libusb/libusb#942 address this PR?

**Comment by harbulot** [comment]
@crroush Thanks for testing, good to know if works for you too. It might be worth commenting directly on libusb/libusb#942 or libusb/libusb#830, since it would probably more visible to the libusb development team.

**Comment by xloem** [comment]
I vaguely recall either you might have ended up doing something equivalent to this, or the main tree mutated so things were slightly different, not sure.  Sorry for leaving it open.

**Pull request closed without merging**
